#!/usr/bin/env php
<?php
ini_set('memory_limit', '20M');

if (strpos('@php_bin@', '@php_bin') === 0)  // not a pear install
{
    require_once dirname(__FILE__).DIRECTORY_SEPARATOR.'iphp.php';
}
else
{
    require_once 'iphp'.DIRECTORY_SEPARATOR.'iphp.php';
}


$opts = array();

// bootstrap options
$tagsFilePath = getcwd() . DIRECTORY_SEPARATOR . 'tags';
if (file_exists($tagsFilePath))
{
    $opts[iphp::OPT_TAGS_FILE] = $tagsFilePath;
}

iphp::main($opts);
